# -*- coding: utf-8 -*-
"""S&P 500 Stock Trends

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14jEbgGpRAnDyItkYcaIfa8cv4-ljpITu
"""

# S&P 500 Stock Trends – Python (Individual, Investment)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.rcParams['figure.figsize'] = (12,6)
sns.set_style("whitegrid")
df = pd.read_csv("/content/all_stocks_5yr.csv")
df.head()
df.info()
# Convert date column to datetime
df['date'] = pd.to_datetime(df['date'])

# Sort properly for time-series calculations
df = df.sort_values(['Name', 'date'])

# Check missing values
df.isnull().sum()
df['daily_return'] = df.groupby('Name')['close'].pct_change()
total_return = df.groupby('Name').agg(
    start_price=('close', 'first'),
    end_price=('close', 'last')
)
#Que.1 Which companies delivered the highest total returns over 5 years?

total_return['total_return_%'] = (
    (total_return['end_price'] / total_return['start_price'] - 1) * 100
)
top_10 = total_return.sort_values(
    'total_return_%', ascending=False
).head(10)

top_10
plt.bar(top_10.index, top_10['total_return_%'])
plt.title("Top 10 S&P 500 Companies by 5-Year Total Return")
plt.ylabel("Total Return (%)")
plt.xticks(rotation=45)
plt.show()
sector_map = {
    # Technology
    'AAPL':'Technology','MSFT':'Technology','GOOGL':'Technology','GOOG':'Technology',
    'AMZN':'Technology','META':'Technology','NVDA':'Technology','INTC':'Technology',

    # Financials
    'JPM':'Financials','BAC':'Financials','WFC':'Financials','C':'Financials',
    'GS':'Financials','MS':'Financials','AXP':'Financials',

    # Energy
    'XOM':'Energy','CVX':'Energy','COP':'Energy','EOG':'Energy','SLB':'Energy'
}

df['Sector'] = df['Name'].map(sector_map)

# Keep only mapped companies
sector_df = df.dropna(subset=['Sector'])

#Que.2 How do risk (volatility) and return compare across sectors?

sector_stats = sector_df.groupby(['Sector','Name']).agg(
    avg_return=('daily_return','mean'),
    volatility=('daily_return','std')
).reset_index()
sector_summary = (
    sector_stats
    .groupby('Sector')[['avg_return','volatility']]
    .mean()
)

sector_summary
plt.scatter(sector_summary['volatility'], sector_summary['avg_return'])

for sector in sector_summary.index:
    plt.text(
        sector_summary.loc[sector,'volatility'],
        sector_summary.loc[sector,'avg_return'],
        sector
    )

plt.xlabel("Risk (Volatility)")
plt.ylabel("Average Daily Return")
plt.title("Risk vs Return Across Sectors")
plt.show()

#Que.3 How correlated are Tech, Finance & Energy sectors?

sector_prices = (
    sector_df.groupby(['date','Sector'])['close']
    .mean()
    .unstack()
)
sector_returns = sector_prices.pct_change()
correlation_matrix = sector_returns.corr()

correlation_matrix
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
plt.title("Correlation Between Major Sectors")
plt.show()

#Que.4 Equal-Weight vs Sector-Weighted Portfolio Performance

equal_weight_returns = df.groupby('date')['daily_return'].mean()
equal_weight_cumulative = (1 + equal_weight_returns).cumprod()
sector_weights = {
    'Technology': 0.4,
    'Financials': 0.3,
    'Energy': 0.3
}

sector_df['weight'] = sector_df['Sector'].map(sector_weights)

sector_weighted_returns = (
    sector_df.groupby('date')
    .apply(lambda x: np.average(x['daily_return'], weights=x['weight']))
)

sector_weighted_cumulative = (1 + sector_weighted_returns).cumprod()
plt.plot(equal_weight_cumulative, label='Equal-Weight Portfolio')
plt.plot(sector_weighted_cumulative, label='Sector-Weighted Portfolio')
plt.legend()
plt.title("Portfolio Performance Comparison (5 Years)")
plt.ylabel("Cumulative Growth")
plt.xlabel("Date")
plt.show()
print("Top 10 Companies by 5-Year Return:")
print(top_10)

print("\nSector Risk-Return Summary:")
print(sector_summary)

print("\nSector Correlation Matrix:")
print(correlation_matrix)